# Generated by Django 3.2.5 on 2022-02-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_chain_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='chain_size',
            new_name='has_sizes',
        ),
    ]
